#include "HIMACAnal.hh"
void PhysicsAnal(){
	TFile* CH2File = new TFile("CH2Run/CH2_1M_cor.root");
	TTree* CH2Tree = (TTree*)CH2File->Get("tree");
	TFile* CFile = new TFile("CH2Run/Carbon_1M_cor.root");
	TTree* CTree = (TTree*)CFile->Get("tree");
	TH1D* CH2_U = new TH1D("CH2_U","CH2_U",100,-5,5);
	TH1D* CH2_D = new TH1D("CH2_D","CH2_D",100,-5,5);
	TH1D* C_U = new TH1D("C_U","C_U",100,-5,5);
	TH1D* C_D = new TH1D("C_D","C_D",100,-5,5);
	TCanvas* c1 = new TCanvas("c1","c1",900,900);
	c1->Divide(2,2);
	c1->cd(1);
	CH2Tree->Draw("0.025*(tdc_cor[2]-tdc_cor[3])/2>>CH2_U","tdc[2]+tdc[3]>0&&tdc[4]+tdc[5]>0");
	c1->cd(2);
	CH2Tree->Draw("0.025*(tdc_cor[4]-tdc_cor[5])/2>>CH2_D","tdc[2]+tdc[3]>0&&tdc[4]+tdc[5]>0");
	c1->cd(3);
	CTree->Draw("0.025*(tdc_cor[2]-tdc_cor[3])/2>>C_U","tdc[2]+tdc[3]>0&&tdc[4]+tdc[5]>0");
	c1->cd(4);
	CTree->Draw("0.025*(tdc_cor[4]-tdc_cor[5])/2>>C_D","tdc[2]+tdc[3]>0&&tdc[4]+tdc[5]>0");
	vector<double> CH2U_spec,CH2D_spec,CU_spec,CD_spec;
	vector<double> pos;
	double CH2Uent = CH2_U->GetEffectiveEntries();
	double CH2Dent = CH2_D->GetEffectiveEntries();
	double CUent = C_U->GetEffectiveEntries();
	double CDent = C_D->GetEffectiveEntries();
	int nb = CH2_U->GetNbinsX();
	TGraph* CH2Ug= new TGraph();
	TGraph* CH2Dg= new TGraph();
	TGraph* CUg= new TGraph();
	TGraph* CDg= new TGraph();
	TGraph* PhUg= new TGraph();
	TGraph* PhDg= new TGraph();
	for(int ib = 0; ib< nb;++ib){
		pos.push_back(CH2_U->GetBinCenter(ib+1));
		CH2U_spec.push_back(CH2_U->GetBinContent(ib+1)/CH2Uent);
		CH2D_spec.push_back(CH2_D->GetBinContent(ib+1)/CH2Dent);
		CU_spec.push_back(C_U->GetBinContent(ib+1)/CUent);
		CD_spec.push_back(C_D->GetBinContent(ib+1)/CDent);
		CH2Ug->AddPoint(pos.at(ib),CH2U_spec.at(ib));
		CH2Dg->AddPoint(pos.at(ib),CH2D_spec.at(ib));
		CUg->AddPoint(pos.at(ib),CU_spec.at(ib));
		CDg->AddPoint(pos.at(ib),CD_spec.at(ib));
		PhUg->AddPoint(pos.at(ib),CH2U_spec.at(ib)-CU_spec.at(ib));
		PhDg->AddPoint(pos.at(ib),CH2D_spec.at(ib)-CD_spec.at(ib));
	}
	TCanvas* c2 = new TCanvas("c2","c2",50,50,900,900);
	c2->Divide(2,2);
	c2->cd(1);
	CH2Ug->Draw();
	CH2Ug->SetTitle("CH2Spectrum_U");
	CH2Ug->SetLineColor(kRed);
	CH2Ug->SetLineWidth(3);
	CUg->Draw("same");
	CUg->SetLineColor(kBlue);
	CUg->SetLineWidth(3);
	CUg->SetTitle("CarbonSpectrum_U");
	c2->cd(2);
	PhUg->Draw();
	PhUg->SetTitle("DifferentialSpectrum_U");
	c2->cd(3);
	CH2Dg->Draw();
	CH2Dg->SetLineColor(kRed);
	CH2Dg->SetLineWidth(3);
	CH2Dg->SetTitle("CH2Spectrum_D");
	CDg->Draw("same");
	CDg->SetLineColor(kBlue);
	CDg->SetLineWidth(3);
	CDg->SetTitle("CarbonSpectrum_D");
	c2->cd(4);
	PhDg->Draw();
	PhDg->SetTitle("DifferentialSpectrum_D");
}
